### ISSUE TITLE
I see nothing preventing Java 7 on RedHat / Centos / Scientific 6.2

### ISSUE THREAD

**Issue by jgn** [puppetlabs/puppetlabs-java#40]
https://github.com/puppetlabs/puppetlabs-java/blob/master/manifests/params.pp#L25

Not sure why the < 6.3

I see plenty of evidence that Java 7 is routine on many versions of RedHat, Centos, and Scientific:

http://www.oracle.com/technetwork/java/javase/compatibility-417013.html (maybe sound or AWT issues?)

http://www.if-not-true-then-false.com/2010/install-sun-oracle-java-jdk-jre-7-on-fedora-centos-red-hat-rhel/

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
