### ISSUE TITLE
Support ensured => purged and/or ensured => absent

### ISSUE THREAD

**Issue by jgn** [puppetlabs/puppetlabs-java#41]
It is not uncommon to want to REMOVE something.

Therefore, it would be helpful to support ensure => purged and/or ensure => absent.

There seems to be a bug in either Puppet 2.7 or the Oracle RPM that makes ensure => purged not work (it always says created).

A workaround is something like this for init.pp:

```
  validate_re($version, 'purged|present|installed|latest|^[._0-9a-zA-Z:-]+$')

  # deleted

  case $version {
    'purged': {
      exec {
        "removepackage_$use_java_package_name":
        # Do it "manually" because either Puppet RPM handling bad, or Java RPM can't handle
        command => "/usr/bin/yum -y erase $use_java_package_name",
        onlyif  => "/bin/rpm -ql $use_java_package_name";
      }    
    }
    default: {
      package { 'java':
        ensure => $version,
        name   => $use_java_package_name,
      }
    }
  }
```

**Comment by gdubicki** [comment]
I think that this issue should stay open to be visible as a missing feature, @chelnak. I just had to implement it myself in our code wrapping the use of this module.

**Comment by chelnak** [comment]
Hey @gdubicki - is this something you'd be interested in submitting a pull request for?
