### ISSUE TITLE
AArch64 support

### ISSUE THREAD

**Issue by 0Rick0** [puppetlabs/puppetlabs-java#514]
## Use Case
The ARM architecture, more specifically AArch64, is getting more popular.
The current implementation only supports x86 and alike installations, but not for any other architecture.

## Describe the Solution You Would Like
I would like the ability to use this module to install Java on an AArch64 machine.

## Describe Alternatives You've Considered
- Directly installing the java package with the package manager
  - This pulls operating system specific logic to the calling module.

## Additional Context
I've created a branch that works for our specific use case.
But I'm not entirely sure it will handle all environments as expected.
https://github.com/0Rick0/puppetlabs-java/tree/feature/support-aarch64

It might also be useful to support other architectures like MIPS, PPC and ARMHF

**Comment by chelnak** [comment]
Hey @0Rick0, would you like to submit your change in a PR? We can see how it runs against our test infra.

**Comment by 0Rick0** [comment]
I've opened the PR

**Comment by chelnak** [comment]
Thank you 😄
