### ISSUE TITLE
Expand the README

### ISSUE THREAD

**Issue by mcandre** [puppetlabs/puppetlabs-java#53]
The README is really sparse right now. Could we please expand it, to answer questions like:
- How do we specify Java version(s) to install?
- How do we install JDKs and/or JREs?
- How do we install Oracle vs Open JVMs?

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄

**Comment by mcandre** [comment]
or reopen this one
