### ISSUE TITLE
Include Subversions in java::download archive paths

### ISSUE THREAD

**Issue by sd-z** [puppetlabs/puppetlabs-java#532]
## Use Case
When upgrading GraalVM Java Subversions over Puppet (i.e. jdk 17.0.4 -> graalvm-22.2 and jdk 17.0.5->graalvm-22.3) my current way to provision needs a workaround in order to function: 
```
file {'/tmp/jdk-0-linux-x64.tar.gz':
    ensure => absent
  }
java::download {'GraalVM-22.3':
    ensure => 'present',
    java_se => 'jdk',
    version => '17',
    version_major => '0',
    version_minor => '5',
    package_type => 'tar.gz',
    url=> 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java17-linux-amd64-22.3.0.tar.gz',
    basedir => '/opt/java',
  } 

```
This is due to the naming of the archive package in download.pp as it does not include subversions. Therefore, if still existing the old archive file will be used and the update will not be successful.
## Describe the Solution You Would Like
Include the $version and $minor_release in the naming of the archive-name  resulting in _jdk-17-0-5-linux-x64.tar.gz_

## Additional Context
I have already included the changes in a [fork ](https://github.com/puppetlabs/puppetlabs-java/compare/main...sd-z:puppetlabs-java:main)and will do a PR if no objections are raised.

**Comment by jordanbreen28** [comment]
Closing this as PR has now been merged. 
Thanks @sd-z!
