### ISSUE TITLE
facter error if no java is installed

### ISSUE THREAD

**Issue by robertc99** [puppetlabs/puppetlabs-java#538]
version 9.0.0 produces a facter error if the module is installed on a machine with no java installation.
This happens even if the module isnt being called since its happening at fact resolution.
The error is

Error: Facter: Error while resolving custom fact fact='java_version', resolution='<anonymous>': unexpected return

**Comment by sircubbi** [comment]
Same problem here. Rolled back to the old version for now.

**Comment by jordanbreen28** [comment]
Thanks for raising this and bringing this to our attention @robertc99.
If you visit the forge, a newer release of this module (v9.0.1) should have resolved this issue, so I'll go ahead and close this. 
I'll keep this issue open for a while to allow you to test this out.
Thanks again.

**Comment by xorpaul** [comment]
I can confirm that the error disappears when using `v9.0.1` 
Thanks @jordanbreen28 for solving it and @robertc99 for raising the issue.

**Comment by sircubbi** [comment]
> I can confirm that the error disappears when using `v9.0.1` Thanks @jordanbreen28 for solving it and @robertc99 for raising the issue.

Rolled out `v9.0.1` here too, which solved the issue.

**Comment by jordanbreen28** [comment]
Thank you for confirming @xorpaul & @sircubbi!
In that case, I'll go ahead and close the issue.
